# Generated by Django 5.1.5 on 2025-02-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_project_category_alter_project_project_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='no_code_development',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='website_design',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
